### ISSUE TITLE
USER STORY: View Recipe List

### ISSUE THREAD

**Issue by EJFleet** [EJFleet/pp4-my-cookbook-blog#1]
As a **Site User** I can **view a list of recipes** so that **select one to read**.
- **Tasks**:
    - [x] Design a recipe list view to show each recipe’s title, preview, image, and author.
    - [x] Create a link to each recipe’s full detail page.
  - **Acceptance Criteria**:
    - [x] Users can access a list of recipes.
    - [x] Each recipe entry shows title, image, description and date published.
    - [x] Recipes are listed in a grid or list format with pagination for easy browsing.
