### ISSUE TITLE
USER STORY: View Recipe

### ISSUE THREAD

**Issue by EJFleet** [EJFleet/pp4-my-cookbook-blog#2]
As a **Site User** I can **click on a recipe** so that **read the full text**.
 - **Tasks**:
    - [x] Create a detail view for each recipe, showing the full content.
    - [x] Create a URL for each recipe.
    - [x] Display the recipe’s title, image, author, date, description,ingredients and method.
  - **Acceptance Criteria**:
    - [x] Clicking on a recipe opens its full content page.
    - [x] Recipe title, image, author, date, description,ingredients and method are displayed.
