### ISSUE TITLE
USER STORY: Contact Form

### ISSUE THREAD

**Issue by EJFleet** [EJFleet/pp4-my-cookbook-blog#20]
As a **Site User**, I can **contact the site owner** so that I can **give feedback or ask questions.**
  - **Tasks**:
    - [ ] Create a contact form with fields for name, email, and message.
    - [ ] Link the contact form to the admin’s contact email or database.
  - **Acceptance Criteria**:
    - [ ] Users can submit a contact form.
    - [ ] Admin receives the form submission with user details.
