### ISSUE TITLE
USER STORY: View the Number of Likes on each Recipe

### ISSUE THREAD

**Issue by EJFleet** [EJFleet/pp4-my-cookbook-blog#3]
As a **Site User ** I can **view the number of likes on each recipe** so that I can **see which is the most popular**.
- **Tasks**:
    - [ ] Add a “like” counter on each recipe entry.
    - [ ] Display the total number of likes on each recipe’s detail page.
  - **Acceptance Criteria**:
    - [ ] Users can see the total like count on each recipe.
    - [ ] A “like” or “unlike” button is available on each recipe.
