### ISSUE TITLE
USER STORY: Log in to Account for Registered User

### ISSUE THREAD

**Issue by EJFleet** [EJFleet/pp4-my-cookbook-blog#31]
As a **Registered User**, I can **log in to my account** so that I can **interact with the site content.**
  - **Tasks**:
    - [x] Add a login form for existing users.
    - [x] Add a navbar element that displays 'logged in' if a registered user is logged in.
  - **Acceptance Criteria**:
    - [x] Registered users can log in to their accounts.
    - [x] Registerd users can see that they are logged in by viewing the the nav bar.
