### ISSUE TITLE
DEV: Install Django environment

### ISSUE THREAD

**Issue by EJFleet** [EJFleet/pp4-my-cookbook-blog#43]
As a **developer**, I can **install Django and the project's supporting libraries** so that I can **create the Django project and app**.

---

**Tasks**:
- [ ] Install Django and the supporting libraries.
- [ ] Create the `requirements.txt` file and add Django and installed libraries to it.

**Acceptance Criteria**:
- [ ] Successful installation of Django and gunicorn.
- [ ] Successful installation of PostgreSQL and psycopg2.
- [ ] Successful installation of Cloudinary.
