### ISSUE TITLE
USER STORY: View the Team page

### ISSUE THREAD

**Issue by EJFleet** [EJFleet/pp4-my-cookbook-blog#54]
As a **Site User**, I can **view a Team page** so that I can **learn more about site's creators.**
  - **Tasks**:
    - [x] Design the Team page layout with separate cards for each Team Member
    - [x] Write and format job title, location and bio for each Team Member
    - [x] Create a navigation link to the Team page in the main menu.
  - **Acceptance Criteria**:
    - [x] The Team page is accessible via the main navigation menu.
    - [x] Each team member is displayed, with the blog owner being in the first position
