### ISSUE TITLE
USER STORY: Delete Team Member

### ISSUE THREAD

**Issue by EJFleet** [EJFleet/pp4-my-cookbook-blog#55]
As a **Site Admin**, I can **delete a Team Member** so that I can **remove or reset information as needed.**
  - **Tasks**:
    - [x] Ensure there is a delete option with a confirmation modal in the Admin panel
  - **Acceptance Criteria**:
    - [x] Admin can delete Team Member with confirmation.
    - [x] Upon deletion, the Team Member is no longer visible on the Team page to site users.
