### ISSUE TITLE
USER STORY: Recipe Search by Title

### ISSUE THREAD

**Issue by EJFleet** [EJFleet/pp4-my-cookbook-blog#7]
As a **Site User**, I can **search for recipes by title** so that I can **find specific recipes.**
  - **Tasks**:
    - [x] Implement a search bar where a user can search by keywords in the recipe title.
    - [x] Display relevant search results in a list or grid view.
  - **Acceptance Criteria**:
    - [x] Users can use a search bar to find recipes by title.
    - [x] Relevant search results display in a list or grid view.
